### ISSUE TITLE
Networking API UDP peer_addr Missing

### ISSUE THREAD

**Issue by pinkforest** [lunatic-solutions/lunatic#110]
Whilst working on https://github.com/lunatic-solutions/lunatic-rs/issues/17 at https://github.com/lunatic-solutions/lunatic-rs/pull/33
I realised that we don't have peer_addr() in host when we connect() and whilst using recv() and send()
If I would cache it in UdpSocket via connect() that would make UdpSocket mutable on connect() which doesn't match std's

**Comment by bkolobara** [comment]
I think we should add it. At the same time we could add `peer_addr` for `TcpStream` too.
