### ISSUE TITLE
0.10 hasn't been released on crates.io

### ISSUE THREAD

**Issue by philpax** [lunatic-solutions/lunatic#119]
Trying out the new version of https://github.com/lunatic-solutions/chat and just noticed that `cargo install lunatic-runtime` still gives me 0.9. I've sidestepped this for now by using ` cargo install -f --git https://github.com/lunatic-solutions/lunatic.git`.

**Comment by withtypes** [comment]
We were planning this week to merge QUIC support. We had some problems with `s2n-quic` crate so it will take a day or two, then we will make a release.

**Comment by bkolobara** [comment]
It's finally out: https://github.com/lunatic-solutions/lunatic/releases/tag/v0.10.0
