### ISSUE TITLE
Allow tests to return Result

### ISSUE THREAD

**Issue by tqwewe** [lunatic-solutions/lunatic#143]
Normal tests in Rust allow you to return `Result<T, E>` which lets you use `?`.

This feature would be nice to have with `#[lunatic::test]`s. Currently, returning a Result from a test causes it to fail.

**Comment by bkolobara** [comment]
Is fixed in https://github.com/lunatic-solutions/lunatic-rs/commit/7ff7c2379bd53e20092ecd6e8aca57b495c2a6ef
