### ISSUE TITLE
Port of permission flags from deno

### ISSUE THREAD

**Issue by HeavyRain266** [lunatic-solutions/lunatic#172]
Hi, this could be particurally useful for extended security and sandboxing.

By default, anything which runs on Deno, doesn't have internet access, read/write operations, env reading etc. until you explicitely allow it by running `--allow-net --allow-read --allow write --allow-env`. For example `--allow-net` on Windows will display prompt where you accept or deny internet access. It may feel annoying for users but you can easly write a wrapper script in powershell or bash.

**Comment by bkolobara** [comment]
We do this for some stuff right now. The current directory is always pre-opened, but if you want access to others you need to map them directly with `--dir=/tmp`. We could add flags for networking too.

I personally think, opposite of Deno, that majority of the APIs should be enabled by default and disabled through the command line. I wrote last year a bit more in detail about this topic: https://lunatic.solutions/blog/sandboxin-for-developers-and-operators/

**Comment by HeavyRain266** [comment]
Sounds good, thanks!

I'm really interested in sandboxing for security and something like flatpak doesn't fit well for cloud-native services and daemons since it's mostly meant for desktop apps.
