### ISSUE TITLE
F# to Rust

### ISSUE THREAD

**Issue by ShalokShalom** [lunatic-solutions/lunatic#219]
How does Rust code run on Lunatic? Since Lunatic itself is written in Rust, it probably needs to separate binding. But can I just compile F# code to Rust (with [Fable](https://jkone27-3876.medium.com/compile-f-to-rust-22cf5aa9021)) and it runs? 

Or do I need to write a special binding for that?
Thanks a lot

**Comment by bkolobara** [comment]
Rust code that runs on lunatic is compiled to WebAssembly first. This is different from the Rust code that **is** the runtime, that compiles to native machine code.

If you can compile F# directly to WebAssembly, you don't need to compile it to Rust. Just run the generated .wasm module directly on lunatic.

**Comment by ShalokShalom** [comment]
I can't compile directly to WebAssembly. Bolero is the only opportunity, and that is a web framework. I like to compile it to Rust, **in order** to compile it to WebAssembly. 

Going by what you say, is this possible. 
Correct?

**Comment by bkolobara** [comment]
I think this could work, but I have never attempted to do something like that.
