### ISSUE TITLE
Lunatic homepage is down

### ISSUE THREAD

**Issue by ShalokShalom** [lunatic-solutions/lunatic#228]
I guess this project is unmaintained anyway, but for the case that somebody still cares for it:

The homepage is down

**Comment by withtypes** [comment]
@ShalokShalom thanks for letting us know, fixed!

**Comment by ShalokShalom** [comment]
Is Lunatic still maintained?

**Comment by withtypes** [comment]
@ShalokShalom no, @bkolobara has been focused on another project https://flawless.dev/ I've been working on something else, too. @tqwewe works on https://github.com/tqwewe/kameo 

The ecosystem, WASI/component model also seems to be moving slow.
