### ISSUE TITLE
Stdout/Stderr not "Process-safe"

### ISSUE THREAD

**Issue by theduke** [lunatic-solutions/lunatic#41]
Currently it seems like there is no locking of `stdout` and `stderr` between processes, which leads to intermingled output when printing from different processes.

This might of course also be related to the WASI implementation in wasmtime.

Also, this is not necessarily something that has to be fixed, I'm sure there are performance tradeoffs here.

I also noticed that trying to lock stdout, stderr handles results in nothing being printed. Which again is probably a limitation of the Rust wasi build and/or wasmtime.

**Comment by bkolobara** [comment]
In our WASI implementation writes to stdout and sterr acquire a lock:
https://github.com/lunatic-solutions/lunatic/blob/main/src/api/wasi/api.rs#L324

This means that each call to the host function `wasi_snapshot_preview1 ::fd_write` will lock while writing to stdout/err. It may just be that the guest language (Rust?) when compiled to .wasm generates multiple invocation of `fd_write`. Between theses calls there are no locks and the output can get intermingled. Especially if you use a macro like `println!` it may generate multiple `fd_write` calls.

A simple solution at the moment would be just to pre-format a string for stdout and directly invoke `fd_write` passing the string to it. If you just pass one string to `println!` it should also result in an atomic write?

> I also noticed that trying to lock stdout, stderr handles results in nothing being printed. Which again is probably a limitation of the Rust wasi build and/or wasmtime.

This locking should be happening in the guest and should work fine. If you could create an minimum reproducible code snippet, I would like to take a deeper look at it.

**Comment by theduke** [comment]
Yeah, as you correctly guesses the problem is with Rust and `println!`.

But regarding the locking, there is an example here: https://github.com/theduke/lunatic-bench/blob/main/src/bin/spawner.rs

```
eprintln!("pre locking");
let out = std::io::stdout();
let mut lock = out.lock();
std::io::Write::write_all(&mut lock, b"hello").unwrap();
```

Only "pre locking" is printed.

**Comment by bkolobara** [comment]
I just re-tested this and it looks like it's fixed.
