### ISSUE TITLE
Add a testing framework to the vm

### ISSUE THREAD

**Issue by bkolobara** [lunatic-solutions/lunatic#91]
After trying to find a nice testing solution for code running on lunatic (see https://github.com/lunatic-solutions/rust-lib/issues/8) over the last few months, I concluded that it is probably impossible to do so without direct support from the vm.

There is an [issue tracking custom testing frameworks for Rust](https://github.com/rust-lang/rust/issues/50297), but it didn't see almost any progress in the last 5 years and I don't see this changing soon. [Other solutions](https://www.infinyon.com/blog/2021/04/rust-custom-test-harness/) relay on libraries like [inventory](https://crates.io/crates/inventory) that require specific life-before-main solutions that don't work in Wasm code. This basically leaves us with only one way forward, provide a testing mode inside of the vm and decorate Rust guest code with a custom macro (`#[lunatic::test]`) that exposes tests to the vm.

I would at the same time use this opportunity to introduce sub-commands in the CLI. E.g `lunatic run file.wasm`, `lunatic test file.wasm `, and maybe some diagnostics in the future `lunatic inspect file.wasm `. If you run `lunatic run file.wasm` the vm would behave like it did until now. Load the wasm file, look for a `_start` function, spawn a process from it and wait until the process finishes.

The new testing mode would behave differently, it would look up all exported functions starting with `__lunatic_test_` and spawn a process from them. If the process finishes without trapping the test would be marked as `OK`, otherwise as `FAIL`. The testing mode would expose a few additional host functions to allow the tested process to name the test and change the configuration (`should_trap=true`?). This would automatically parallelise all test execution and let the schedule auto balance any waiting. This would also just be the starting point (unit tests), later we can extend the functionality to cover more complicated testing scenarios.

Maybe we should also provide some heuristics for automatically detecting the testing mode? Rust guest code can configure only one runner (e.g. `lunatic run`) that is also used when you run `cargo test`. It could be useful for the `lunatic` command to default to run mode, except if it detects some environment variables that indicate tests running. This would provide a seamless integration with `cargo test` & `cargo run` for Rust's use case.

I'm wonderring how other languages, like AssemblyScript could integrate with this? From what I have seen, AssemblyScript doesn't have a standardised test runner. Having a lunatic custom one wouldn't impact the developer experience? @jtenner

**Comment by zhamlin** [comment]
Is there any work that can be started to help move this issue forward?
The testing situation on lunatic is something I'd like to help improve.

**Comment by bkolobara** [comment]
Hi @zhamlin, jtenner started some work on this: https://github.com/lunatic-solutions/lunatic/pull/93 https://github.com/lunatic-solutions/lunatic/pull/92.

I will take some time to finish the VM part soon, but the rust library `#[test]` macro still needs some work: https://github.com/lunatic-solutions/rust-lib/blob/main/lunatic-macros/src/lib.rs#L21. It should create a wrapper function in the form of `__lunatic_test_*` around the test, so that it can be picked up by the VM. It would also be nice to support some properties, such as `panic=true`. Is this something you would be interested working on?

**Comment by zhamlin** [comment]
Sure I can take a stab at it.

Is there an example in the rust-lib of creating an exported wasm function?
I see the macro you linked creates a function, but not sure if that's what you meant.

**Comment by bkolobara** [comment]
A rust function can be exported with the annotation `#[export_name = "__lunatic_test_*"]`. Each function will need to have a unique name generated though.
