### ISSUE TITLE
Switch to tokio.rs from async_std

### ISSUE THREAD

**Issue by bkolobara** [lunatic-solutions/lunatic#94]
I would like to propose switching back to tokio.rs as lunatic's async executor.

Many projects are moving away from async_std (https://github.com/launchbadge/sqlx/issues/1669) and some "high profile" rust community members are advocating for everyone to just adopt tokio. There are many other good reasons to switch to tokio, like more active development and bigger community & library support.

We are already using tokio's `select!` macro and have it as a dependency. The only reason why I decided to switch to async_std is the fact that async_std's `TcpStream` is `Clone`. This allows us to expose a simple primitive to guest code that can be shared between processes. And having one process read from the `TcpStream` and another write to it is a common pattern in lunatic.

As I hinted already in [this comment](https://github.com/lunatic-solutions/lunatic/issues/76#issuecomment-1002218417), we could introduce a `split` function and `ReadTcpStream` & `WriteTcpStream` primitive to work around this. This would also provide us with more security, because you can't accidentally write to `WriteTcpStream` from 2 processes (exclusively owned). At the same time, many (all?) other io_uring based async runtimes also provide this split approach to `TcpStreams` and introducing this change wouldn't stop us from adopting another async executor in the future.

**Comment by sleipnir** [comment]
tokio's scheduler is one of the best schedulers ever implemented and actively maintained by the community. I would go from tokio  for sure

**Comment by jtenner** [comment]
Don't forget udp as well. Is this work difficult?

**Comment by bkolobara** [comment]
> Don't forget udp as well. Is this work difficult?

UDP should work the same way as now. Clone-able through the Arc. https://docs.rs/tokio/latest/tokio/net/struct.UdpSocket.html

**Comment by indiv0** [comment]
I'd recommend doing some basic benchmarks just to make sure this doesn't introduce a big performance regression but aside from that no real concerns about switching to tokio.

The logic around splitting the read & write streams seems solid.

**Comment by Darksonn** [comment]
It is worth mentioning that the Tokio `TcpStream` type can also be put in an `Arc` and cloned in that manner. However, using it in this situation is more annoying because you have to use the `ready`/`readable`/`writable` and `try_read`/`try_write` methods to read and write to it when it is wrapped in an `Arc`. But it _is_ possible.

**Comment by bkolobara** [comment]
Thanks for the tip @Darksonn! I didn't know it could be used that way.
